package selenium.ide;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

public class TestInuyashaAuthor {
    private WebDriver driver;
    private final static String AUTHOR = "Rumiko Takahashi";
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","trunk/src/test/java/selenium/Driver/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test1() {
        // Test name: Test1
        // Step # | name | target | value | comment
        // 1 | open | https://www.lafeltrinelli.it/?gclid_Cj0KCQiAjJOQBhCkARIsAEKMtO1AoxvZ2i4qu3vNb3xUKQ2eNlqRtYA-DyX7zbfN6UTJ43VOOzWdkx0aAm-rEALw_wcB&awaid=9507&gclid=Cj0KCQiAjJOQBhCkARIsAEKMtO1AoxvZ2i4qu3vNb3xUKQ2eNlqRtYA-DyX7zbfN6UTJ43VOOzWdkx0aAm-rEALw_wcB |  |
        driver.get("https://www.lafeltrinelli.it/?gclid_Cj0KCQiAjJOQBhCkARIsAEKMtO1AoxvZ2i4qu3vNb3xUKQ2eNlqRtYA-DyX7zbfN6UTJ43VOOzWdkx0aAm-rEALw_wcB&awaid=9507&gclid=Cj0KCQiAjJOQBhCkARIsAEKMtO1AoxvZ2i4qu3vNb3xUKQ2eNlqRtYA-DyX7zbfN6UTJ43VOOzWdkx0aAm-rEALw_wcB");
        // 2 | setWindowSize | 945x1012 |  |
        driver.manage().window().setSize(new Dimension(945, 1012));
        // 3 | click | css=.cc-header-button--menu .cc-icon |  |
        driver.findElement(By.cssSelector(".cc-header-button--menu .cc-icon")).click();
        // 4 | click | linkText=Libri |  |
        driver.findElement(By.linkText("Libri")).click();
        // 5 | click | css=.cc-open:nth-child(1) .cc-content-menu-item:nth-child(1) .cc-link-text |  |
        driver.findElement(By.cssSelector(".cc-open:nth-child(1) .cc-content-menu-item:nth-child(1) .cc-link-text")).click();
        // 6 | click | linkText=Inuyasha. Wide edition. Vol. 3 |  |
        driver.findElement(By.linkText("Inuyasha. Wide edition. Vol. 3")).click();
        // 7 | mouseOver | linkText=Rumiko Takahashi |  |
        {
            WebElement element = driver.findElement(By.linkText(AUTHOR));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 8 | assertText | linkText=Rumiko Takahashi | Rumiko Takahashi |
        assertThat(driver.findElement(By.linkText(AUTHOR)).getText(), is(AUTHOR));
    }
}
