package com.example.comics.model;

public enum Categories {
    ACTION, ADVENTURE, BIOGRAPHY, COMEDY, DRAMA, HORROR, HIGHSCHOOL,
    MANGA, LOVE, SLICE_OF_LIFE, SCI_FI, SUPERHEROES, TEEN_ROMANCE,
    TEEN_DRAMA, ROMANCE, VAMPIRES, ZOMBIES
}
