package com.example.comics.model;

public enum Categories {
    ACTION, ADVENTURE, BIOGRAPHY, COMEDY, DRAMA, HORROR, HIGHSCHOOL,
    MANGA, MARVEL, DC_COMICS, LOVE, SLICE_OF_LIFE, SCI_FI, SHONEN, SHOJO,
    SUPERNATURAL, SUPERHEROES, TEEN_ROMANCE,
    TEEN_DRAMA, ROMANCE, VAMPIRES, ZOMBIES
}
